### ISSUE TITLE
migrate from payments.saturn.tech to payouts.saturn.tech

### ISSUE THREAD

**Issue by gruns** [filecoin-saturn/contracts-ui#37]
payouts is the more apt word here

**Comment by AmeanAsad** [comment]
https://payouts.saturn.tech/ is live now and set as the primary domain.

**Comment by gruns** [comment]
we should 301 redirect from the old payments.saturn.tech to the new payouts.saturn.tech

**Comment by AmeanAsad** [comment]
Redirects resolved here: https://github.com/filecoin-saturn/contracts-ui/commit/6c6fbf50bc0b78e7d8e8a74e5ca6eec39b662407 and also modified on cloudflare dns
