### ISSUE TITLE
Release Funds causing Error   Error performing transaction  View Original Message

### ISSUE THREAD

**Issue by vorburger** [filecoin-saturn/contracts-ui#46]
I'm trying to https://docs.saturn.tech/claim-your-rewards on https://payouts.saturn.tech,

and after much trouble even getting this far (FYI https://github.com/filecoin-saturn/L1-node/issues/419 and https://github.com/ChainSafe/filsnap/pull/260),

am now stuck with the following error message shown in a sort of popup when click _Release All Funds_ or _Release Selected:_ 

`Error   Error performing transaction  View Original Message`

The _Original Message_ is empty however.

The Console shows _Chain "Filecoin Mainnet" does not support multicall._ but that pops up even before I click _Release_ so I suspect that's not the root cause?

How do we further debug this?

**Comment by AmeanAsad** [comment]
Hello @vorburger unfortunately the UI might fail for some wallet types. FilSnap is a very new tool so claiming with it might yield issues as above. We'll take a look at those issues to try and resolve. 

For the meantime our recommended wallet for the UI is MetaMask or you can try claiming through the CLI as well.

**Comment by vorburger** [comment]
I'm now trying to Release Funds using the CLI instead of https://payouts.saturn.tech, but am now stuck with https://github.com/filecoin-saturn/contracts/issues/70.

**Comment by vorburger** [comment]
It finally worked for me now; the "trick" that I was missing was simply to stop using MetaMask **Flask** with https://github.com/ChainSafe/filsnap and just use regular MetaMask!
